### HTTP Request to create a new company
POST http://localhost:8080/compliance-tracker/api/v1/companies
Content-Type: application/json

{
  "name": "XYZ",
  "industry": "TECHNOLOGY",
  "address": {
    "street": "Storgata 2",
    "postalCode": "0484",
    "city": ""
  },
  "primaryContact": {
    "name": "John Doe",
    "email": "john.doe@gmail.com",
    "phoneNumber": "+4723334373"
  },
  "countryOfOrigin": "NORWAY",
  "notes": "Leading tech company."
}

### HTTP Request to get all companies
GET http://localhost:8080/compliance-tracker/api/v1/companies
Accept: application/json

### HTTP Request to get a specific company by ID
GET http://localhost:8080/compliance-tracker/api/v1/companies/36f49cc0-0144-48cd-88e8-3d6366811674
Accept: application/json

### HTTP Request to update an existing company
PUT http://localhost:8080/compliance-tracker/api/v1/companies/621a5972-d980-4012-8b6e-bb46d8210a30
Content-Type: application/json

{
  "name": "Acme Corporation",
  "industry": "TECHNOLOGY",
  "address": {
    "street": "Storgata 3",
    "postalCode": "0484",
    "city": ""
  },
  "primaryContact": {
    "name": "John Doe",
    "email": "john.doe1@gmail.com",
    "phoneNumber": "+4723314373"
  },
  "countryOfOrigin": "SWEDEN",
  "notes": "updated: Leading tech company."
}

### HTTP Request to delete a company
DELETE http://localhost:8080/compliance-tracker/api/v1/companies/621a5972-d980-4012-8b6e-bb46d8210a30
Accept: application/json
